const notes = [
  { category: 'Cultura & velocidade', title: 'Quanto tempo vive uma estética?', className: 'waves', paragraphs: ['Quando uma linguagem visual se espalha, ela também se torna mais fácil de reconhecer e reproduzir. A repetição pode transformar descoberta em fórmula.', 'Uma leitura útil acompanha o percurso: quem começou, quem reinterpretou e em quais contextos a estética ainda carrega significado. A pergunta não é apenas se ela está em alta, mas o que as pessoas estão dizendo com ela.'] },
  { category: 'Plataformas & pertencimento', title: 'O que existe entre um feed e uma comunidade?', className: 'circles', paragraphs: ['Um feed reúne publicações. Uma comunidade constrói relações, referências compartilhadas e formas de reconhecer quem faz parte.', 'Para entender uma mudança cultural, vale olhar para as respostas, as piadas internas e as adaptações. O significado muitas vezes está na conversa que uma publicação provoca, não apenas na publicação.'] },
  { category: 'Memória & criação', title: 'O futuro também nasce do remix.', className: 'stripes', paragraphs: ['Retomar uma referência não significa repetir seu sentido. Uma imagem, uma roupa ou um som ganha outra leitura quando encontra um novo contexto.', 'Investigar um remix é seguir essas duas histórias: de onde veio o material e por que ele faz sentido agora. É nessa distância entre origem e uso que uma nova linguagem pode aparecer.'] },
]
export default function Observatory() {
  return (
    <section className="observatory section-shell" id="observatory" aria-labelledby="observatory-title"><p className="eyebrow">O observatório</p><h2 id="observatory-title">Notas de um mundo<br /><em>que não para.</em></h2><div className="journal-grid">{notes.map(note => <article className="journal-entry" key={note.title}><div className={'journal-art journal-art--' + note.className} aria-hidden="true"><i /><i /><i /></div><p className="journal-category">{note.category}</p><h3>{note.title}</h3><details><summary>Ler a reflexão <span className="disclosure-mark" aria-hidden="true">+</span></summary><div className="journal-body">{note.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div></details></article>)}</div></section>
  )
}
